// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwSFmijBthkklX3bXNVnkSlOCG2dOfGpY',
    appId: '1:924289933629:web:ca4f48483de20a7804a554',
    messagingSenderId: '924289933629',
    projectId: 'db-web-quests',
    authDomain: 'db-web-quests.firebaseapp.com',
    databaseURL: 'https://db-web-quests-default-rtdb.firebaseio.com',
    storageBucket: 'db-web-quests.appspot.com',
    measurementId: 'G-6EWWEG3QM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmhRKnt0R0ieeuVQJJi7peoSmNzxNcPQs',
    appId: '1:924289933629:android:ad22ebe24b8d677304a554',
    messagingSenderId: '924289933629',
    projectId: 'db-web-quests',
    databaseURL: 'https://db-web-quests-default-rtdb.firebaseio.com',
    storageBucket: 'db-web-quests.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_ZR5ofCcSSPt9L3DrwMVYu5fLDmry2es',
    appId: '1:924289933629:ios:4114a4491b1d074704a554',
    messagingSenderId: '924289933629',
    projectId: 'db-web-quests',
    databaseURL: 'https://db-web-quests-default-rtdb.firebaseio.com',
    storageBucket: 'db-web-quests.appspot.com',
    iosBundleId: 'com.example.testeFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_ZR5ofCcSSPt9L3DrwMVYu5fLDmry2es',
    appId: '1:924289933629:ios:813a43db9e18a46604a554',
    messagingSenderId: '924289933629',
    projectId: 'db-web-quests',
    databaseURL: 'https://db-web-quests-default-rtdb.firebaseio.com',
    storageBucket: 'db-web-quests.appspot.com',
    iosBundleId: 'com.example.testeFirebase.RunnerTests',
  );
}
